solicitante:
  nome: "siga"
  sobrenome: "DevSecOps"

homologacao:
  pre_aprovado: true
  restricao_horario_inicio: "07:00"
  restricao_horario_fim: "23:59"
  
treinamento:
  pre_aprovado: true
  restricao_horario_inicio: "17:30"
  restricao_horario_fim: "23:00"

producao:
  pre_aprovado: false
  restricao_horario_inicio: "21:30"
  restricao_horario_fim: "23:59"